title_left: happyz
title_right: leaf
title_domain: happyzleaf.com
description: Yup, that's me. You're probably wondering how I ended up in this situation.
keywords: Marco Montanari, happyzleaf, portfolio
url: https://happyzleaf.com
baseurl: ""
cover: /assets/images/author.jpg

# google_analytics:
twitter_username: happyzlife

markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

sass:
  sass_dir: assets/scss
  style: compressed # expanded

author:
  name: Marco Montanari
  mail: marco@montanari.cc

plugins:
  - jekyll-sitemap
  - bourbon

exclude:
  - _ignore
