title_left: happyz
title_right: leaf
description: Yup, that's me. You're probably wondering how I ended up in this situation.
keywords: Marco Montanari, happyzleaf, portfolio
url: https://happyzleaf.com
baseurl: ""
cover: ""

# google_analytics:
twitter_username: happyzlife

markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

sass:
  sass_dir: assets/scss
  style: compressed # expanded

author:
  name: Marco Montanari
  mail: marco@montanari.cc
  avatar: /assets/images/avatar.png

plugins:
  - jekyll-sitemap
  - bourbon

compress_html:
  comments: ["<!--", "-->"]

exclude:
  - _ignore
  - .idea
